import Image from 'next/image';
import React from 'react';
import Link from 'next/link';
import { metacareLogo } from "../../public/assets/Projects/index.js";

const Metacare = () => {
  return (
    <section id='certificates' className='w-full h-full bg-[#0c0e0f] text-white py-28'>
      <h1 className='text-3xl md:text-2xl lg:text-3xl uppercase tracking-[10px] font-semibold text-center'>
        Metacare
      </h1>

      {/* VER O QUE SE PASSA COM O 2XL */}
      {/* Images display (only 2 per div)*/}
      <div className='w-full h-[470px] flex flex-col items-center justify-center
      md:flex md:flex-col md:h-[850px] md:px-40
      lg:flex lg:flex-col lg:h-[850px]
      xl:flex xl:flex-col xl:h-[850px] 
      2xl:flex 2xl:flex-row 2xl:h-[800px] 
      mt-16 gap-10'>
        
        {/* Image 1 */}

          <div className='w-[300px] h-[423px] md:w-[560px] md:h-[793px] relative overflow-hidden group'>
            <Image className='w-full h-full object-cover scale-100'
            src={metacareLogo} 
            alt="cimg1" 
            />
          </div>
          
      </div>

      <p className='text-3xl pt-5 px-10 lg:px-40 lg:pt-20 md:text-3xl font-medium md:leading-relaxed text-textColor'>
        MetaCare Health aims to give ownership over individual health data and real time monitoring of various medical data, 
        using IoT wearable devices. We intent to leverage Dynamic NFT technology in order to create a personal avatar and digital twin, 
        allowing not only data generated by IoT devices but also verified medical information, to be replicated and stored. Furthermore, 
        we seek to provide a reward-based system to incentivize users to pursue a healthy lifestyle, as well as an educational platform 
        to help individuals learning about health-related problems, with a gamified learning experience. <br />
        <br />
        As a blockchain researcher with a deep knowledge of the ecosystem and scientific education, I provided valuable advisory 
        services to MetaCare Health. Leveraging my expertise, I helped the team explore the potential of blockchain technology and 
        new approachs for NFTs in creating a personal avatar and digital twin for storing and replicating medical data.
      </p>
      


    </section>
  )
}

export default Metacare
